'use client'
import './globals.css'
import type { Metadata } from 'next'
import AOS from 'aos';
import 'aos/dist/aos.css'
import { useEffect } from 'react';

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

interface Props {
  children: React.ReactNode
}

export default function RootLayout({ children, }: Props) {
  useEffect(() => {
    AOS.init();
  
  }, [])
  
  return (
    <html lang="en">
      <body>
        {children}
      </body>
    </html>
  )
}
